### ISSUE TITLE
Check crosswalk plugin

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#106]
This will bring chromium webview for older android phones
https://crosswalk-project.org/documentation/cordova.html

**Comment by spastai** [comment]
```
I20160520-06:56:33.252(3) (android:http://localhost:12584/cordova.js:1185) deviceready has not fired after 5 seconds.
I20160520-06:56:33.254(3) (android:http://localhost:12584/cordova.js:1178) Channel not fired: onDOMContentLoaded
I20160520-06:56:34.547(3)? E/MeteorWebApp(19545): Download failure
I20160520-06:56:34.548(3)? E/MeteorWebApp(19545): com.meteor.webapp.WebAppException: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible
I20160520-06:56:34.548(3)? E/MeteorWebApp(19545):   at com.meteor.webapp.WebAppLocalServer.shouldDownloadBundleForManifest(WebAppLocalServer.java:367)
I20160520-06:56:34.549(3)? E/MeteorWebApp(19545):   at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:131)
I20160520-06:56:34.550(3)? E/MeteorWebApp(19545):   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
I20160520-06:56:34.550(3)? E/MeteorWebApp(19545):   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20160520-06:56:34.551(3)? E/MeteorWebApp(19545):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I20160520-06:56:34.552(3)? E/MeteorWebApp(19545):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I20160520-06:56:34.553(3)? E/MeteorWebApp(19545):   at java.lang.Thread.run(Thread.java:818)
```
