### ISSUE TITLE
Cordoba dependencies error

### ISSUE THREAD

**Issue by spastai** [vilnius/vilnius-carpool#139]
```
I20160614-10:38:12.170(3)? E/MeteorWebApp( 6616): Download failure
I20160614-10:38:12.171(3)? E/MeteorWebApp( 6616): com.meteor.webapp.WebAppException: Skipping downloading new version because the Cordova platform version or plugin versions have changed and are potentially incompatible
I20160614-10:38:12.173(3)? E/MeteorWebApp( 6616):   at com.meteor.webapp.WebAppLocalServer.shouldDownloadBundleForManifest(WebAppLocalServer.java:367)
I20160614-10:38:12.174(3)? E/MeteorWebApp( 6616):   at com.meteor.webapp.AssetBundleManager$1.onResponse(AssetBundleManager.java:131)
I20160614-10:38:12.174(3)? E/MeteorWebApp( 6616):   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
I20160614-10:38:12.176(3)? E/MeteorWebApp( 6616):   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
I20160614-10:38:12.177(3)? E/MeteorWebApp( 6616):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
I20160614-10:38:12.178(3)? E/MeteorWebApp( 6616):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
I20160614-10:38:12.180(3)? E/MeteorWebApp( 6616):   at java.lang.Thread.run(Thread.java:818)
```

**Comment by spastai** [comment]
http://stackoverflow.com/questions/36363217/how-to-update-cordova-plugin-device-in-my-meteor-project helped on Note4 and S3 for locahost

**Comment by spastai** [comment]
Should progress on staging and production
- [ ] Update staging code with hotfix/0.1.13
- [ ] meteor run android-device --mobile-server=http://stg.arciau.lt 
- [ ] create apk for staging with server http://stg.arciau.lt
